config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
    end
  end
  get 'authentication', to: 'users#authentication'
  devise_for :users
  resources :products
  root 'products#index'
  get 'alert_js', to: 'products#alert_js', as: 'alert_js'
  post 'invite_friend', to: 'users#invite_friend', as: 'invite_friend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  scope :published, -> { where(published: true) }

  def word_count
    name.split(' ').length
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :auth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
    protect_from_forgery with: :null_session
    before_action :basic_auth

     def index
         @products = Product.all
         render json: { products: @products }
     end


    def create
        @product = Product.create(product_params)   
        if @product.save
          render json: @product
        else
          render json: { errors: @product.errors }, status: 422
        end
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
          render json: @product
        else
          render json: { errors: @product.errors }, status: 422
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
    
        head :no_content
    end
    

  private

    def product_params
      params.require(:product).permit(:name, :price)
    end

    def basic_auth 
      authenticate_or_request_with_http_basic do |user, token|
        user = User.find_by_email(user)
        if user.auth_token == token
          sign_in user
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!

  def index
    @products = Product.all

  end

  def alert_js

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    respond_to do |format|
      format.html { redirect_to products_path }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.update(params[:id], product_params)
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def invite_friend
    to_email = params[:email]
    from_email = current_user.email
    UserMailer.create_invite(from_email, to_email, Time.now).deliver_now
  end

  def authentication
    user = User.find_by_email(params[:email])
    if  user.valid_password?(params[:password])
      render json: { token: user.auth_token }
    end  
  end
#exponer un endpoint authentication que reciba el usuario y el password de un usuario y retorne el token
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBootstrapModals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @product, remote: true do |f| %>
        <div class="modal-body">
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_field :price, class: "form-control input-lg", placeholder: "Precio del producto" %>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/products/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
  <td>
    <%= link_to "Editar", edit_product_path(product), remote: true %>
  </td>
</tr>

app/views/products/alert_js.js.erb
console.log("Hola Mundo!");
alert('hola mundo!')

app/views/products/create.js.erb
<% if @product.errors.empty? %>
  $('table tbody').append('<%= j render "row", product: @product %>');
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>

app/views/products/edit.js.erb
$('<%= j render "form", title: "Editar Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Products</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 text-right">
      <%= link_to "Nuevo Producto", new_product_path, remote: true, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <%= render "row", product: product %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/index_first.html.erb
<button class="btn btn-primary show-btn">Mostrar alerta</button>

<%= link_to "Mostrar alerta (con remote true)", alert_js_path, remote: true, class: 'btn btn-primary' %>

<script>
  new ProductsView();
</script>

app/views/products/new.js.erb
$('<%= j render "form", title: "Nuevo Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/update.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @product.id %>').replaceWith(' <%= j render "row", product: @product %>');
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Products Page</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>